### PR TITLE
Application layout.

### PR DESCRIPTION
**Pull request by j1nma**
## Summary
* I followed the commands of the Kick-Off card for initializing the project layout (src and test folders, sln).

## Trello Card Link
https://trello.com/c/6i0eX8cW/1-kick-off

## Screenshots
image

## Notes
Made some mistakes at the beginning with another branch, now *layout* is what I wanted. Pull request available.

### CODE REVIEW

**Review by gzamudio — CHANGES_REQUESTED** [review]
.vscode/ and obj/ folder are in the repo. remove them and push again. if you dont know how to do it write me on slack

**Comment by j1nma** [comment]
Done.

**Review by gzamudio — APPROVED** [review]
add empty line at the end of files that do not have it

**Comment by j1nma** [comment]
Done!

**Pull request merged**
